
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Formatter;
import oracle.jdbc.OracleCallableStatement;
import oracle.jdbc.OracleTypes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rishi
 */
public class Professor_EditHomeWork extends javax.swing.JFrame {

    /**
     * Creates new form Professor_EditHomeWork
     */
    Gradiance globalParent;
    int hw_id;
    java.util.Date BeginDate =null ,EndDate= null;
    java.sql.Date BeginSql = null;
    java.sql.Date EndSql = null;
    DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
 
    public Professor_EditHomeWork(java.awt.Frame parent,boolean modal) {
        globalParent = (Gradiance)parent;
        globalParent.globalProfessor_CourseHomePage.editHomeWorkInstance = this;
        hw_id = globalParent.globalProfessor_CourseHomePage.selectHomeworkInstance.hw_id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        numberAttemptsLabel = new javax.swing.JLabel();
        correctAnswerPointsLabel = new javax.swing.JLabel();
        incorrectAnswerPointsLabel = new javax.swing.JLabel();
        scoreSelectionCriteriaLabel = new javax.swing.JLabel();
        difficultyLevelLabel = new javax.swing.JLabel();
        startDateText = new javax.swing.JTextField();
        endDateText = new javax.swing.JTextField();
        numberofAttemptsText = new javax.swing.JTextField();
        inCorrectAnswerPointsText = new javax.swing.JTextField();
        scoreSelectionCmbBox = new javax.swing.JComboBox();
        correctAnswerPointsText = new javax.swing.JTextField();
        difficultylevelText = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        startDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startDateLabel.setText("StartDate");

        endDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endDateLabel.setText("EndDate");

        numberAttemptsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberAttemptsLabel.setText("NumberAttempts");

        correctAnswerPointsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correctAnswerPointsLabel.setText("+Ve Answer Points");

        incorrectAnswerPointsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incorrectAnswerPointsLabel.setText("-Ve Answer Points");

        scoreSelectionCriteriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreSelectionCriteriaLabel.setText("Score Selection Criteria");
        scoreSelectionCriteriaLabel.setToolTipText("Score Selection Criteria");

        difficultyLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        difficultyLevelLabel.setText("Difficulty Level");

        inCorrectAnswerPointsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inCorrectAnswerPointsTextActionPerformed(evt);
            }
        });

        scoreSelectionCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Max", "Latest", "Average" }));
        scoreSelectionCmbBox.setToolTipText("ScoreSelectionCriteria");
        scoreSelectionCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreSelectionCmbBoxActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scoreSelectionCriteriaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberAttemptsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(endDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(correctAnswerPointsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(incorrectAnswerPointsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(difficultyLevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(startDateText, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(endDateText, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(numberofAttemptsText, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(inCorrectAnswerPointsText, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(scoreSelectionCmbBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(difficultylevelText, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                            .addComponent(correctAnswerPointsText, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberAttemptsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberofAttemptsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctAnswerPointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correctAnswerPointsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incorrectAnswerPointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inCorrectAnswerPointsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreSelectionCriteriaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreSelectionCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(difficultyLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(difficultylevelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(BackButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        try
        {
            BeginDate = formatter.parse(startDateText.getText());
            EndDate = formatter.parse(endDateText.getText());
            BeginSql = new java.sql.Date(BeginDate.getTime());
            EndSql = new java.sql.Date(EndDate.getTime());
            String sql ="{call UPDATE_HW(?,?,?,?,?,?,?,?)}";
            Connection conn =Gradiance.conn ;
            CallableStatement callableStatement = conn.prepareCall(sql);
            callableStatement.setInt(1, hw_id);
            callableStatement.setDate(2, BeginSql);
            callableStatement.setDate(3,EndSql);
            callableStatement.setInt(4,Integer.parseInt(numberofAttemptsText.getText()));
            callableStatement.setInt(5,Integer.parseInt(correctAnswerPointsText.getText()));
            callableStatement.setInt(6,Integer.parseInt(inCorrectAnswerPointsText.getText()));
            callableStatement.setString(7,scoreSelectionCmbBox.getSelectedItem().toString());
            callableStatement.setInt(8,Integer.parseInt(difficultylevelText.getText()));
            //callableStatement.registerOutParameter(7,java.sql.Types.INTEGER);
            callableStatement.execute();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        finally
        {
            this.setVisible(false);
            globalParent.globalProfessor_CourseHomePage.setVisible(true);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.setVisible(false);
        globalParent.globalProfessor_CourseHomePage.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try
        {
            String sql ="{call EDIT_HW(?,?)}";
            Connection conn =Gradiance.conn ;
            CallableStatement callableStatement = conn.prepareCall(sql);
            callableStatement.setInt(1, hw_id);
            callableStatement.registerOutParameter(2,OracleTypes.CURSOR);
            callableStatement.execute();
            ResultSet result = ((OracleCallableStatement)callableStatement).getCursor(2);
            
            callableStatement.execute();
            while(result.next())
            {
                startDateText.setText(result.getDate(1).toString());
                endDateText.setText(result.getDate(2).toString());
                numberofAttemptsText.setText(new Integer(result.getInt(3)).toString());
                correctAnswerPointsText.setText(new Integer(result.getInt(4)).toString());
                inCorrectAnswerPointsText.setText(new Integer(result.getInt(5)).toString());
                scoreSelectionCmbBox.addItem(result.getString(6));
                difficultylevelText.setText(new Integer(result.getInt(7)).toString());
            }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void inCorrectAnswerPointsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inCorrectAnswerPointsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inCorrectAnswerPointsTextActionPerformed

    private void scoreSelectionCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreSelectionCmbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreSelectionCmbBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Professor_EditHomeWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Professor_EditHomeWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Professor_EditHomeWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Professor_EditHomeWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Professor_EditHomeWork().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel correctAnswerPointsLabel;
    private javax.swing.JTextField correctAnswerPointsText;
    private javax.swing.JLabel difficultyLevelLabel;
    private javax.swing.JTextField difficultylevelText;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JTextField endDateText;
    private javax.swing.JTextField inCorrectAnswerPointsText;
    private javax.swing.JLabel incorrectAnswerPointsLabel;
    private javax.swing.JLabel numberAttemptsLabel;
    private javax.swing.JTextField numberofAttemptsText;
    private javax.swing.JComboBox scoreSelectionCmbBox;
    private javax.swing.JLabel scoreSelectionCriteriaLabel;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField startDateText;
    // End of variables declaration//GEN-END:variables
}
