
import java.awt.Frame;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.OracleCallableStatement;
import oracle.jdbc.OracleTypes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sree
 */
public class Professor_Home extends javax.swing.JFrame {

    public Update_Password globalupdpwd ;
    public Update_Account globalUpdateAcct;
    public Professor_AddCourse globalAddCourse;
    public Professor_CourseHomePage globalCourseHomePage;
    Gradiance GlobalParent;
    public String CurrentCourseToken;
    ArrayList al = new ArrayList();
    /**
     * Creates new form Professor_Home
     */
    public Professor_Home(Frame parent, boolean modal) {
        GlobalParent = (Gradiance)parent;
        GlobalParent.globalProfessor_Home = this;
        initComponents();
    }
    
    private int getCourseToken(String courseName)
    {
        try
        {
            String sql = "select COURSETOKENID from COURSE C1,COURSEOFFERINGS C2 where "
                    +"C1.COURSEID = C2.COURSEID and C1.COURSENAME = ?";
            PreparedStatement stmnt = Gradiance.conn.prepareStatement(sql);
            stmnt.setString(1, courseName);
            ResultSet rs = stmnt.executeQuery();
            rs.getInt(1);
            return 0;
        }
        catch(Exception ex)
        {
            
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        updatepassword_button = new javax.swing.JButton();
        updateaccount_button = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();
        addcourses_button = new javax.swing.JButton();
        selectcourse_combobox = new javax.swing.JComboBox();
        go_button = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Display Courses :");

        updatepassword_button.setText("Update Password");
        updatepassword_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepassword_buttonActionPerformed(evt);
            }
        });

        updateaccount_button.setText("Update Account");
        updateaccount_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateaccount_buttonActionPerformed(evt);
            }
        });

        logout_button.setText("Log Out");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        addcourses_button.setText("Add Courses");
        addcourses_button.setEnabled(GlobalParent.isProfessorMode);
        addcourses_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcourses_buttonActionPerformed(evt);
            }
        });

        selectcourse_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectcourse_comboboxActionPerformed(evt);
            }
        });

        go_button.setText("Go");
        go_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addcourses_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(go_button))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(selectcourse_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updatepassword_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateaccount_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(208, 336, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectcourse_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(go_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addcourses_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(updatepassword_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateaccount_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatepassword_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepassword_buttonActionPerformed
        // TODO add your handling code here:
        
        Update_Password objUpPass = new Update_Password(GlobalParent, true);
        objUpPass.setVisible(true);
        
    }//GEN-LAST:event_updatepassword_buttonActionPerformed

    private void addcourses_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcourses_buttonActionPerformed
        // TODO add your handling code here:
        Professor_AddCourse objProfAC = new Professor_AddCourse(GlobalParent,true);
        this.setVisible(false);
        objProfAC.setVisible(true);
    }//GEN-LAST:event_addcourses_buttonActionPerformed

    private void updateaccount_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateaccount_buttonActionPerformed
        // TODO add your handling code here:
        Update_Account objUpAcc = new Update_Account(GlobalParent,true);
        this.setVisible(false);
        objUpAcc.setVisible(true);
    }//GEN-LAST:event_updateaccount_buttonActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       GlobalParent.setVisible(true);
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void selectcourse_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectcourse_comboboxActionPerformed
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_selectcourse_comboboxActionPerformed

    private void go_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_buttonActionPerformed
        // TODO add your handling code here:
        //CurrentCourseToken = getCourseToken(selectcourse_combobox.getSelectedItem().toString());
        int index = selectcourse_combobox.getSelectedIndex();
        CurrentCourseToken = al.get(index).toString();
        Professor_CourseHomePage objProfCHP = new Professor_CourseHomePage(GlobalParent, true);
        this.setVisible(false);
        objProfCHP.setVisible(true);
    }//GEN-LAST:event_go_buttonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
        String current_UserName = GlobalParent.UserName;
        String sql ="{call PROFCOURSE_LIST(?,?)}";
            Connection conn =Gradiance.conn ;
            CallableStatement callableStatement = conn.prepareCall(sql);
            callableStatement.setString(1, current_UserName);
            
            callableStatement.registerOutParameter(2,OracleTypes.CURSOR);
            callableStatement.execute();
            ResultSet result = ((OracleCallableStatement)callableStatement).getCursor(2);
            ResultSet count = result;
            
            int i = 0;
            
            while(result.next()){
            selectcourse_combobox.addItem(result.getString(2)+" - "+result.getString(1));
             al.add(i,result.getString(2));
             i++;
            }
        //ResultSet courselist = zadanie.executeQuery(sql);
                } catch (SQLException ex) {
            Logger.getLogger(GridLayoutDemo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Professor_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Professor_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Professor_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Professor_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Professor_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcourses_button;
    private javax.swing.JButton go_button;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout_button;
    private javax.swing.JComboBox selectcourse_combobox;
    private javax.swing.JButton updateaccount_button;
    private javax.swing.JButton updatepassword_button;
    // End of variables declaration//GEN-END:variables
}
