/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author shashankgoud
 */
import java.awt.Frame;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oracle.jdbc.OracleCallableStatement;
import oracle.jdbc.OracleTypes;

public class Your_Classes extends javax.swing.JFrame {

    /**
     * Creates new form YourClasses
     */
    Gradiance globalParent;
    String course_name ="";
    String course_tokenid="";
    
    public Your_Classes(Frame parent, boolean modal) {
        globalParent = (Gradiance)parent;
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        
                jButton2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
                jButton3.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
                jButton4.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
                         jButton5.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
                         jButton6.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
            jButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("Gradiance");

        jButton2.setText("HomePage");

        jButton3.setText("Update Password");

        jButton4.setText("Update Account");

        jButton5.setText("Logout");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
       
                
        jButton6.setText("Open");

        jLabel1.setText("Choose the Course");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>  
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) { 
     
     this.setVisible(false);
     globalParent.globalHomePage.setVisible(true);
    }  
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { 
     
     this.setVisible(false);
    globalParent.globalHomePage.globalupdpwd.setVisible(true);
    }  
       private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) { 
     
     this.setVisible(false);
    globalParent.globalHomePage.globalUpdateAcct.setVisible(true);
    }  
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) { 
     
     this.setVisible(false);
     globalParent.CleanLocalFields();
     globalParent.setVisible(true);
    }
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { 
     
     try{

String command = "C:\\Program Files\\Internet Explorer\\IEXPLORE.EXE http://www.gradiance.com/" ;

Process link = Runtime.getRuntime().exec(command); 
}
catch(Exception ex){
System.out.println("cannot execute command. " +ex); 
}
    }
     private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) 
     { 
     
        String current_UserName = globalParent.UserName ;
        this.course_name = jTextField1.getText();
        int courseId = Integer.parseInt(this.course_name);
        globalParent.globalHomePage.globalAssignments_Due.jLabel1.setText(course_name) ;
        String course_check ="";
        try {
            String sql ="{call Check_Courses(?,?,?,?)}";
            
            CallableStatement callableStatement = Gradiance.conn.prepareCall(sql);
            callableStatement.setString(1,current_UserName);
            callableStatement.setInt(2, courseId);
            callableStatement.registerOutParameter(3,java.sql.Types.INTEGER);
            callableStatement.registerOutParameter(4,java.sql.Types.VARCHAR);
            callableStatement.execute();
            int Ret_Val = callableStatement.getInt(3);
            course_tokenid = callableStatement.getString(4); 
                if(Ret_Val == 1)
                {
                    this.setVisible(false);
                    globalParent.globalHomePage.globalcourse_homepage.setVisible(true);
                }
                else if(Ret_Val == 2)
                {
                    this.setVisible(false);
                    Gradiance.isProfessorMode = false;
                    globalParent.globalProfessor_Home = new Professor_Home(globalParent, true);
                    globalParent.globalProfessor_Home.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Please select the valid courseId");
                }
        }catch (SQLException ex) {
            Logger.getLogger(Gradiance.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        String courses = "";
        String current_UserName = globalParent.UserName;
        try 
        {
            Connection conn = Gradiance.conn;
            String sql ="{call Registered_Courses(?,?)}";
            CallableStatement callableStatement = conn.prepareCall(sql);
            callableStatement.setString(1,current_UserName);
            callableStatement.registerOutParameter(2,OracleTypes.CURSOR);
            callableStatement.execute();
            ResultSet result = ((OracleCallableStatement)callableStatement).getCursor(2);
            
        while(result.next())
        {
            courses = courses + "\n" + result.getString(1) + " - " + result.getString(2); 
            
        }
        jTextArea1.setText(courses);
        }  
        catch (SQLException ex) {
            Logger.getLogger(Gradiance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                 

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
